# This file has been generated by node2nix 1.11.1. Do not edit!
{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [],
}: let
  sources = {};
in {
  "@github/copilot" = nodeEnv.buildNodePackage {
    name = "_at_github_slash_copilot";
    packageName = "@github/copilot";
    version = "0.0.365";
    src = fetchurl {
      url = "https://registry.npmjs.org/@github/copilot/-/copilot-0.0.365.tgz";
      sha512 = "VXW+FHQkjTA5TGcVzvfUbmUr9AilBPDYU89iPFc5mZlZqDMaOpN4X2twYn9qJBO9y0Vhmorzwxaa4aQdsUYZ9w==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "GitHub Copilot CLI brings the power of Copilot coding agent directly to your terminal.";
      homepage = "https://github.com/github/copilot-cli/#readme";
      license = "SEE LICENSE IN LICENSE.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
