# This file has been generated by node2nix 1.11.1. Do not edit!
# Modified to use nodejs_22 for @github/copilot

{pkgs ? import <nixpkgs> {
    inherit system;
  }, system ? builtins.currentSystem, nodejs ? pkgs.nodejs_22}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv lib runCommand writeTextFile writeShellScript;
    inherit pkgs nodejs;
    python2 = pkgs.python3;  # python2 is deprecated, use python3
    libtool = if pkgs.stdenv.isDarwin then pkgs.cctools or pkgs.darwin.cctools else null;
  };
in
import ./node-packages.nix {
  inherit (pkgs) fetchurl nix-gitignore stdenv lib fetchgit;
  inherit nodeEnv;
}
