{
  pkgs,
  lib,
  systemType,
  ...
}: {
  imports =
    [
      ./chezmoi
      ./claude-code
      ./cmake
      ./coreutils
      ./direnv
      ./emacs
      ./fd
      ./fzf
      ./gcc
      ./ghq
      ./git
      ./gitstatus
      ./glibtool
      ./gnumake
      ./libtool
      ./markitdown
      ./mermaid-cli
      ./nixvim
      ./ripgrep
      ./tmux
      ./tree
      ./unar
      ./vim
      ./vips
    ]
    ++ lib.optionals (systemType != "wsl") [
      ./alt-tab
      ./claude-desktop
      ./anki
      ./chatgpt
      ./chawan
      ./cmux
      ./copilot
      ./discord
      ./doll
      ./drawio
      ./ghostty
      ./homerow
      ./jankyborders
      ./jetbrains
      ./jordanbaird-ice
      ./hammerspoon
      ./mucommander
      ./notunes
      ./orion
      ./raycast
      ./slack
      ./voiceink
      ./wezterm
    ]
    ++ [
      ./zsh
    ];
}
